### ISSUE TITLE
Ability to start chatbot on startup

### ISSUE THREAD

**Issue by Wrexthor** [chrisrude/oobabot-plugin#12]
Unless im missing something there is no way to initiate the bot automatically. Would be helpful not having to enter the interface and start it manually.

**Comment by chrisrude** [comment]
Thanks for the feedback!

You are correct -- currently you can load the plugin automatically, but it won't start the bot.  That's actually a great idea that I totally spaced on for some reason. :)

I'll work on it for the next release.

**Comment by chrisrude** [comment]
This should be fixed with the 0.2.0 release.  Please let me know if it still occurs after that.

To upgrade, just go into your textgen directory / conda environment and run `pip install oobabot-plugin --upgrade`.

Thanks for the report!
