### ISSUE TITLE
Automatically retry if response is not sent

### ISSUE THREAD

**Issue by cha0sbuster** [chrisrude/oobabot-plugin#13]
Right now, if the bot accidentally tries to talk as someone else, the reply is simply aborted, and a wakeword must be used to retry. This could probably be automatic, with a configurable amount of retries.
Alternatively, you could have it clip the response before the filtered string.

**Comment by chrisrude** [comment]
Thanks for the suggestion!

I'm curious if your model has generated different responses when you retry.  My worry is that if it's using default temperature settings, that it would just generate the same response as it did previously.

In my testing this tends to get better on its own as the bot gets more chat history.  Perhaps including a chat history from a character card would help?  Open to ideas.

**Comment by chrisrude** [comment]
Just confirming, it currently should post the response before the filtered string.  I'm not confident that retrying in this case would help much, as it might just regenerate the same thing as what we decided to drop.

I've seen this be a bigger problem when there isn't much chat history, and that continuing the conversation helps it get the pattern better.  If there is a lot of chat context, increasing the history context should help.
