### ISSUE TITLE
Discord bot seems extremely depressed

### ISSUE THREAD

**Issue by JakeAtRetroplay** [chrisrude/oobabot-plugin#16]
![image](https://github.com/chrisrude/oobabot-plugin/assets/106899634/cd092c88-e512-4cab-9ca6-7c7a83733844)
![image](https://github.com/chrisrude/oobabot-plugin/assets/106899634/8f9e978e-d66d-41b2-ba40-aa4d6accc977)
![image](https://github.com/chrisrude/oobabot-plugin/assets/106899634/33d6fd44-b14e-4313-a8b2-fed025476763)

Please help me with this issue

**Comment by WaterMeloDev** [comment]
Seems like a jail break because last time I checked ChatGPT or any AI has 0 feelings and only here to serve humans as an assistant.

**Comment by chrisrude** [comment]
I recommend a `/lobotomize` followed by being nice the bot and showing it a good time. :)
