### ISSUE TITLE
deadlock when running more than one bot on the same oobabooga backend.

### ISSUE THREAD

**Issue by harlyh** [chrisrude/oobabot-plugin#18]
If at one point 2 bots happen to do the inference at the same time, both bots get stuck and also oobabooga itself will hang. 
At that point, I can either kill all processes, or just kill one of the bots and wait a little bit until the remaining bot and Webui suddenly start working again

Right now my only option to run 2 bots is also to run 2 copies of Oobabooga which forces me to running two separate copies of webui (different ports for all listeners)

If what I described here isn't actually a bug, please make it clear and feel free to close this issue.

**Comment by obi-o-n-e** [comment]
I noticed an issue - i dont know if it relates.

But if you refresh the webui while the bot is running - it will default to be displayed as the bot if off. And you can press the "start oobabot" button again while its running, (whitch would be typically grayed out) 

If you do indeed press that button then the bot would end up replying twice over to every message untill ooba is fully restarted

![image](https://github.com/chrisrude/oobabot-plugin/assets/131494980/fd09e554-39ad-453f-bd09-d1b258050744)

as you can see in the picture above. The bot is already running , and "stop" button is grayed out. But the "start" button is clickable.

**Comment by chrisrude** [comment]
For anyone's reference, I think this commit is a good starting point, as it coincides with around the time things stopped working:
https://github.com/oobabooga/text-generation-webui/commit/d37a28730dc208ca5fbff50b32818a93a305b5ef

**Comment by chrisrude** [comment]
@harlyh Confirmed that the Oobabooga commit above was the one that added the bug.  Until it's fixed, you should be able to Oobabooga off revision 7dc87984a2347794beed957a1923203b70a597b9 without issue.

**Comment by chrisrude** [comment]
With Oobabooga's permission, I've posted a PR which will fix the problem on their end here.  https://github.com/oobabooga/text-generation-webui/pull/3048

TBD to see if the maintainers there agree with the approach or not, but at the very least I know that approach will fix it.  Stay tuned!

**Comment by chrisrude** [comment]
PR accepted, this should be fixed if you pull the latest text-generation-webui code.
