### ISSUE TITLE
Able to start the oobabot twice 

### ISSUE THREAD

**Issue by obi-o-n-e** [chrisrude/oobabot-plugin#19]
I noticed an issue - i dont know if it relates.

But if you refresh the webui while the bot is running - it will default to be displayed as the bot if off. And you can press the "start oobabot" button again while its running, (whitch would be typically grayed out) 

If you do indeed press that button then the bot would end up replying twice over to every message untill ooba is fully restarted

![image](https://github.com/chrisrude/oobabot-plugin/assets/131494980/fd09e554-39ad-453f-bd09-d1b258050744)

as you can see in the picture above. The bot is already running , and "stop" button is grayed out. But the "start" button is clickable.

_Originally posted by @obi-o-n-e in https://github.com/chrisrude/oobabot-plugin/issues/18#issuecomment-1621232435_

**Comment by chrisrude** [comment]
Thanks for the report!  I've landed a fix for this in https://github.com/chrisrude/oobabot-plugin/commit/bb81073decf0fc9d302680fb884100334e5e7039

It should be included in the next release.

**Comment by chrisrude** [comment]
This should be fixed with the 0.2.0 release.  Please let me know if it still occurs after that.

To upgrade, just go into your textgen directory / conda environment and run `pip install oobabot-plugin --upgrade`.

Thanks for the report!
