### ISSUE TITLE
Can't press anything?

### ISSUE THREAD

**Issue by Simplegram** [chrisrude/oobabot-plugin#22]
Every button greyed out and I can't press anything. I just installed the extension following the steps.
![image](https://github.com/chrisrude/oobabot-plugin/assets/34500695/e68268b5-1b5b-48a0-afe5-846a6c00a2d1)

I need to remove ```disabled=""``` in order to unblock all of the buttons.
![image](https://github.com/chrisrude/oobabot-plugin/assets/34500695/24f4fa31-de45-4291-ae42-a542537bd219)

After digging into the code, it seems that the bot token must be 72 or higher while my generated token is 70 chars long.

**Comment by Simplegram** [comment]
After messing with the code that I downloaded locally, I managed to change the token len in ```strings.py``` to 70 and successfully run the bot.

**Comment by chrisrude** [comment]
Interesting.  I haven't yet seen any token of that size, and my understanding is that a 70 character token shouldn't be possible based on my understanding of how they're generated.  I just tried generating a bunch more, and wasn't able to get one that was shorter than 72 characters in length.

Is the token newly generated?

In any case, if you generate a new one, what length is it?

Would it be possible to generate a new one and then send me the old (now invalid) token?  If there are multiple formats, it would be helpful for me to know how the other ones are structured.  The length check isn't there just for the UI, later on the code decodes the token to read some values from it, so it's important to understand how the tokens are structured to make sure that part of the code works too.

Thanks for your help!

**Comment by Simplegram** [comment]
Yes the token is newly generated. Here is my old token: ```ODU0Mjk4ODgwNzkwODg4NDU5.GeiMih.gY_WJSWxKpLCRoV0c_AND0100WoQQszxyKDmfU```

**Comment by chrisrude** [comment]
Added a fix in a7c98300c3f92e911b0b85032060de03a098734c

Thanks for the report!  Apologies for being skeptical initially, it's sometimes hard to tell bugs from simple user errors.

If you want to pull the latest `main` you can get the fix, though I imagine you might have already fixed it yourself.  Alternatively, you could use the oobabot CLI bot in the meantime (which should work as-is), or wait until the next release.

As a bonus, I now now way more than anyone should about how Discord tokens are generated. :)

**Comment by Simplegram** [comment]
Thank you for the fix! Happy to help :)

I also know more now about discord bot token. I thought it was a randomly generated string.
