### ISSUE TITLE
Proper way to update

### ISSUE THREAD

**Issue by BenevolenceMessiah** [chrisrude/oobabot-plugin#23]
Saw the big changes that hit the last couple of days here - incidentally, and I apologize for being a noob - but how would I go about updating to 0.2.0? I did a git pull and attempted reinstalling via conda. I also attempted deleting the oobabot directories out of the extensions folder and git cloning fresh. I also ran the update script from the one-click installer in between deleting and git cloning. Any assistance would be greatly appreciated.

**Comment by chrisrude** [comment]
First, activate your text-generation-webui conda environment, if you're using one.

Then
```bash
pip install oobabot-plugin --upgrade
```

is all you need!

I'm thinking folks might like it if I put an update notification / button in the app itself, which would make it easier to do remotely.

**Comment by chrisrude** [comment]
I should also add that the oobabooga UI added a method of installing plugins from within the UI... that isn't something that works with `oobabot-plugin` yet.  I might want to add that too, to make initial installs work easier.

**Comment by BenevolenceMessiah** [comment]
> I should also add that the oobabooga UI added a method of installing plugins from within the UI... that isn't something that works with `oobabot-plugin` yet. I might want to add that too, to make initial installs work easier.

Thank you so much for taking the time to assist with this. I'm self taught on all of this stuff, ergo assistance of this nature is especially valued. Might I also ask why this plugin requires the upgrade command? Is it because it also installs in other destination directories via the conda environment? This is by far my favorite extension. Reading the 0.2.0 changelog really got me excited! As long as you're here, is this extension interactive with other extensions? for example, if I were using EdgeGPT locally, would the 'Hey, Bing' activation word carry through to oobabot? What about other extensions like Superbooga? Also, if I load a character following the example .yaml format, will it take the example conversation text into consideration? 

Lastly, as long as you are taking suggestions, is there an easy way to add other slash commands at the user level? That would be pretty solid. Also, I really dig being able to use Stable Diffusion - I don't quite have the computational capacity to run everything simultaneously. I would suggest a way to interact with Midjourney bot. Also, when we do get voice support rolling, it would be solid to use some of these RVC models I trained. I do actually have a list of suggestions and features that would push us closer to an interactive AGI. A lot of it has to do with managing token offloading in accordance with machine modeling human neuroanatomy and how it facilitates long term vs short term. Anyway, I'm rambling. Is there an ideal way I could connect with you and send some ideas? Discord, Facebook, email., etc. just let me know! I'm super excited about this project!
