### ISSUE TITLE
unable to load oobabot

### ISSUE THREAD

**Issue by lths** [chrisrude/oobabot-plugin#25]
I keep getting this error on startup:

2023-07-27 23:50:27 ERROR:Failed to load the extension "oobabot".

Traceback (most recent call last):

  File "/app/modules/extensions.py", line 35, in load_extensions

    exec(f"import extensions.{name}.script")

  File "<string>", line 1, in <module>

  File "/app/extensions/oobabot/script.py", line 7, in <module>

    from oobabot_plugin import bootstrap

ModuleNotFoundError: No module named 'oobabot_plugin'

Anyone know how to resolve this?

**Comment by chrisrude** [comment]
Hi!

From the directory you're running the python3 server.py, could you try running:

```
   pip install oobabot-plugin --upgrade
```

Let me know if this fixes it!

**Comment by lths** [comment]
Hey thanks for the response! So I am running it in a docker container and this did not work.  HOWEVER, what did work is adding the 3 items in the oobabot requirements.txt file into the oobabooga requirements.txt file and rebuilding the whole container.!

**Comment by mwhaite** [comment]
for those of us (me absolutely me) that are a bit slow... could you elaborate on your solution to install this plugin inside the docker container.

**Comment by lths** [comment]
sure thing.

Edit the docker file to add the extension install for the requirements and then run the script.
I am pasting everything i changed starting with the extension install steps:

`COPY extensions/api/requirements.txt /app/extensions/api/requirements.txt
COPY extensions/elevenlabs_tts/requirements.txt /app/extensions/elevenlabs_tts/requirements.txt
COPY extensions/google_translate/requirements.txt /app/extensions/google_translate/requirements.txt
COPY extensions/silero_tts/requirements.txt /app/extensions/silero_tts/requirements.txt
COPY extensions/whisper_stt/requirements.txt /app/extensions/whisper_stt/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/api && pip3 install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/elevenlabs_tts && pip3 install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/google_translate && pip3 install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/silero_tts && pip3 install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/whisper_stt && pip3 install -r requirements.txt

COPY extensions/superbooga/requirements.txt /app/extensions/superbooga/requirements.txt
COPY extensions/web_search/requirements.txt /app/extensions/web_search/requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && pip3 install oobabot
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && pip3 install oobabot-plugin && oobabot-plugin install
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/superbooga && pip3 install -r requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip . /app/venv/bin/activate && cd extensions/web_search && pip3 install -r requirements.txt

COPY requirements.txt /app/requirements.txt
RUN . /app/venv/bin/activate && \
    pip3 install -r requirements.txt

RUN cp /app/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so /app/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so

RUN pip3 install oobabot

RUN pip3 install oobabot-plugin 

COPY /extensions/oobabot/config.yml /oobabot-config.yml


COPY . /app/
ENV CLI_ARGS=""

RUN oobabot-plugin install


CMD . /app/venv/bin/activate && python3 server.py ${CLI_ARGS}`

**Comment by mwhaite** [comment]
do you run ```docker-compose up --build``` after that edit?

**Comment by lths** [comment]
I forgot to mention that you then you add the extensions to the .ENV file under the CLI_args
Mine looks like this:
 `CLI_ARGS= --listen --chat --auto-devices --api --extensions oobabot openai web_search ` 


Once those are added to docker file and ENV file, you run the `docker-compose up --build` and it should rebuild the image with the new extensions.

**Comment by chrisrude** [comment]
Loving folks helping each other out!

Is there interest in a Dockerfile which bundles oobabooga and oobabot together?
