### ISSUE TITLE
Disable unsolicited replies?

### ISSUE THREAD

**Issue by dragos240** [chrisrude/oobabot-plugin#32]
I want my bot to only reply to others if it's pinged and not any other time. Is there a way I can disable unsolicited replies?

**Comment by Timboman** [comment]
Set `unsolicited_channel_cap:` to 0 in the config.yml file

**Comment by dragos240** [comment]
I've done that. That flag when set to 0 disables the maximum number of channels, meaning it will work in any number of channels. It doesn't disable unsolicited replies.

**Comment by chrisrude** [comment]
Fixed in the above commit:

```yaml
  # If set, the bot will not reply to any messages that do not @-mention it or include a
  # wakeword.  If unsolicited replies are disabled, the unsolicited_channel_cap setting will
  # have no effect.
  #   default: False
  disable_unsolicited_replies: true
```
