### ISSUE TITLE
show we're actually using the selected character

### ISSUE THREAD

**Issue by chrisrude** [chrisrude/oobabot-plugin#5]
make it clear what's happening when a character is / isn't selected

**Comment by sidonsoft** [comment]
when using a character, does this override the persona, combine the persona with character or otherwise?

**Comment by chrisrude** [comment]
What's actually happening is that "character" in Gradio == a character .json or .yml file.  When you select a character, it just loads that file as if you passed in a `persona_file` in to oobabot cli.  Meaning it will read that file, and ignore what is in the "ai_name" and "persona" fields.

My plan was to have it hide the "ai_name" and "persona" values when you select a character, and in its place show the replacement values that we've read out of the character file.

**Comment by chrisrude** [comment]
Fix for this landed.  In case anyone is interested, here's a screenshot of what it looks like now when you select a character:
![image](https://github.com/chrisrude/oobabot-plugin/assets/12817326/7cd077c0-3a24-42f6-ae53-37691ae8d2ce)

It shows you what `oobabot` will read out of the character sheet, and disables entry (as you really need to be editing the character sheet directly).

**Comment by sidonsoft** [comment]
with some trial and error I had discovered that wake words needed to be separated by commas and no spaces and that the character selected was added to the end of the wake words list automatically, please update the READ ME file to reflect this.

**Comment by chrisrude** [comment]
was this in the yaml or with the gui?

**Comment by sidonsoft** [comment]
this was before the update, I will update later and test it out

**Comment by chrisrude** [comment]
Just landed a few more tweaks, should be a bit more reasonable now
